__default__:
  prefix: "--time=24:00:00 --mem=4g --partition=norm"
rmats:
  prefix: "--time=24:00:00 --mem=16g --partition=norm"
preparse:
  prefix: "--time=24:00:00 --mem=16g --partition=norm"
parse:
  prefix: "--time=24:00:00 --mem=16g --partition=norm"
sashimiplot:
  prefix: "--time=24:00:00 --mem=16g --partition=norm"
pdfunite:
  prefix: "--time=24:00:00 --mem=16g --partition=norm"
